<b>Autoregressive Integrated Moving Average (ARIMA):</b> The Autoregressive Integrated Moving Average (ARIMA) model is the method is suitable for univariate time series with trend and without seasonal components which is the combination of the differenced autoregressive model with the moving average model.
The AR part of ARIMA indicates that the time series is regressed on its own past data. The MA part of ARIMA indicates that the forecast error is a linear combination of past respective errors.

<b>Simple Exponential Smoothing (SES):</b> Simple Exponential Smoothing (SES) is a forecasting method for univariate time series without trend and seasonal components which is not based on the analysis of the entire historical time series, rather than it uses the weighted averages of past observations where the weights of older observations exponentially decrease.

In [1]:
#importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_excel('ExampleOilMeasurementDaily 2.xlsx')
df.head()

Oil 2018-10-01 00:00:00  1329.6
0  Oil          2018-10-02  1435.2
1  Oil          2018-10-03  1372.1
2  Oil          2018-10-04  1371.7
3  Oil          2018-10-05  1200.0
4  Oil          2018-10-06   978.7

In [3]:
#check for null
df.isnull().sum()

Oil                    0
2018-10-01 00:00:00    0
1329.6                 0
dtype: int64

In [4]:
data=df.iloc[:, 2].values

In [5]:
data

array([1435.2, 1372.1, 1371.7, ...,  119.9,  114.1,  109.9])

In [6]:
#ARIMA
from statsmodels.tsa.arima.model import ARIMA
#model
model_arima = ARIMA(data, order=(1, 1, 1))

In [7]:
#fit the model
model_fit_arima = model_arima.fit()

In [8]:
# make prediction
yhat_arima = model_fit_arima.predict(len(data), len(data), typ='levels')
yhat_arima

array([109.38413406])

In [9]:
#next day predicted change is
forecast_percent_change_arima = ((yhat_arima[0]/data[-1])-1)*100.0
print('Next day predicted change using ARIMA is ',forecast_percent_change_arima)

Next day predicted change using ARIMA is  -0.4693957573189911


In [10]:
#SES
from statsmodels.tsa.holtwinters import SimpleExpSmoothing
#model
model_ses = SimpleExpSmoothing(data)

In [11]:
#fit the model
model_fit_ses = model_ses.fit()

In [12]:
# make prediction
yhat_ses = model_fit_ses.predict(len(data), len(data))
yhat_ses

array([110.59892713])

In [13]:
# next day predicted change is
forecast_percent_change_ses = ((yhat_ses[0]/data[-1])-1)*100.0
print('Next day predicted change using SES is ',forecast_percent_change_ses)

Next day predicted change using SES is  0.6359664471357496
